# Site settings
title: Fokayx, a Ruby Nerd. 
email: fokayx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  From Novice Rubyist to Ruby Diablo.<br>
  從奶油桂花手到暗黑破壞神的紅寶石之路
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fokayx.github.io" # the base hostname & protocol for your site
twitter_username: fokayx
github_username:  fokayx

# Build settings
markdown: kramdown
#
#redcarpet:
#  extensions:[]
#
#highlighter: pygments
